version: "3.8"

services:
  database:
    image: postgres
    container_name: postgres-t1-school
    environment:
      POSTGRES_DB: t1-school
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"